### ISSUE TITLE
Dice So Nice rolls no longer animate, even for public rolls.

### ISSUE THREAD

**Issue by sirrus233** [sPOiDar/fvtt-module-hide-gm-rolls#18]
With the Dice So Nice! module, and this module installed, I would expect to see animated dice for public rolls, and no animations for private/blind/self rolls. Indeed, this was the former behavior.

As of about a week ago, animations no longer show with any roll type, including public.

**Comment by sPOiDar** [comment]
I introduced a setting some time ago to control whether public Dice So Nice rolls are hidden, since DSN handles hiding private rolls itself now. That said, I don't believe I meant to have that option enabled by default, so I'll publish a change that defaults this option to `false`, and clarifies the name of the option.

If you turn off the `Sanitize Dice So Nice! GM Rolls` option, you should get your public rolls back.

**Comment by sPOiDar** [comment]
This will default to false in v0.10.2
