### ISSUE TITLE
Bug - inline called rolls can't be hidden

### ISSUE THREAD

**Issue by Albolynx** [sPOiDar/fvtt-module-hide-gm-rolls#19]
Hello! Thanks for developing this module! Encountered a strange bug that I certainly did not experience before and I'm not sure when it started happening.

Rolls made from clicking on inline setups - for example, a [[/r 1d20]] embedded in the text of an item or journal entry - are not hidden from players even with the "Hide Private GM Rolls" option ticked. All other types of rolls are hidden properly. The inline rolls are still sanitized.

Foundry version: 0.8.9
System: D&D5e 1.4.3
Tested and reproduced with no other modules active, and both on Firefox and Chrome
No errors in the console

**Comment by sPOiDar** [comment]
This looks like a problem in core Foundry - even if you have the roll mode set to `Private GM Roll`, inline rolls from a Journal or similar are rolled in the open (as a GM you can tell, because the background for the roll card is the standard colour, rather than blue). This module only works if Foundry performs the right kind of roll.

I'd suggest this be reported upstream, if it hasn't been already.
