### ISSUE TITLE
Chat card results visible to players

### ISSUE THREAD

**Issue by cojinx303** [sPOiDar/fvtt-module-hide-gm-rolls#26]
A monster attack roll to a targeted player is hidden from players, but the chat card that follows with the results (even with Hide GM Item card selected in module setting) is showing up to players. In a perfect world it would be possible to disable these chat cards entirely (even for me) as it is just duplicate information anyway and apparently non-concealable, though I imagine that's a Foundry Core issue.

**Comment by sPOiDar** [comment]
You're going to have to provide more information, and/or screenshots, because it's not clear to me what you're describing - if you want to hide rolls entirely, and are rolling with `Private GM Roll` enabled, no data should be displayed to players by core foundry.

I would guess that either you're not rolling privately, or there's another module involved that's producing an extra card, but it's hard to tell from your description.

**Comment by sPOiDar** [comment]
I'm going to close this due to lack of response. Feel free to re-open if you have more info.
