### ISSUE TITLE
Hide crit/fumble colours on totals

### ISSUE THREAD

**Issue by manituan** [sPOiDar/fvtt-module-hide-gm-rolls#6]
I've been waiting for something like this module since I started using Foundry, but to start using it I'd love to see this implemented first:
- Remove the colour from the result if the dice roll was 1 (red) or 20 (green). This is revealing to the player the modifier indirectly. 
- Hide the name of the monster/NPC that it's rolling or mask it with an alias. (forget about this one, I've seen there's a module that does that already)
- Attack rolls show the modifiers and damage type.

The first two options could be toggles in the module settings. 
Thank you!

![image](https://user-images.githubusercontent.com/812457/91740182-36d7b100-ebb3-11ea-9997-00c218987f3a.png)

**Comment by sPOiDar** [comment]
1. We should be able to remove the crit/fail colors, though I'd guess you're going to reveal any crits to the players anyway.
2. There are a number of other modules that let you hide or change the names of the speaker for rolls (or use the token name, which can be randomly generated by token mold). I'm not sure if I want to add that to this module - I prefer to see smaller modules that have limited scope.
3. What system is that? Because we're already hiding the roll formula when sanitize is enabled:

| GM | Player |
|-----|----|
| ![Screenshot_20200901_084319](https://user-images.githubusercontent.com/70048780/91775903-a2f7fa80-ec2f-11ea-8558-20dcc8703db6.png) | ![Screenshot_20200901_084412](https://user-images.githubusercontent.com/70048780/91775909-a7241800-ec2f-11ea-91f7-e92a752a7319.png) |

**Comment by manituan** [comment]
1.- I'd appreciate it. Ty
2.- Yes, I realised soon after writing this that there are other modules that do this. 100% agree with you. 
3.- I'm running Pathfinder 2. Should I contact the developers over there?

Thanks!

**Comment by sPOiDar** [comment]
3. They're baking the dice formula into the the flavor text for the roll, so there's no easy way for me to remove it - I'd have to resort to some error-prone text pattern matching to try and strip it out. I don't know if they'd be interested in changing it though, and I'm not sure how deep this is coded into the system - looks like the trigger for the rolls in the char sheet also has this text baked in, so it may be just how the system is written. Probably doesn't hurt to ask if this is easily removed though.

**Comment by sPOiDar** [comment]
I've pushed a change to hide the crit/fumble colours, that will be released soon, so I'm going to close this one out with that. If you hear anything about PF2E one way or the other, please feel free to open a new issue and we'll see if we can do anything sensible here.
